### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by hmhkyaw13** [arilot/zabbix-antminer#3]
Import failed
Details
Created: Item "Temp chip2 chain8" on "AntMiner".
Created: Item "GH/S (RT)" on "AntMiner".
Created: Item "Temp chip2 chain7" on "AntMiner".
Created: Item "Temp chip2 chain6" on "AntMiner".
Created: Item "Fan 6" on "AntMiner".
Created: Item "Fan 3" on "AntMiner".
Incorrect item key "antiminer-zbx-chk["{HOST.CONN}", "{$HOST.PORT}", "{$HTTP.USERNAME}", "{$HTTP.PASSWORD}", "devs.0.freq.temp2_7"]" provided for trigger expression on "AntMiner".

**Comment by hmhkyaw13** [comment]
>

**Comment by hmhkyaw13** [comment]
Issue has been solved i changed antiminer-zbx-chk to antminer-zbx-chk. But i still did not see the data in Graph. Instruction is not clear .
"Make antminer-zbx-chk executable (chmod +x check_dnsbl.sh)"

need to change file name to "check_dnsbl.sh" ?

**Comment by daniel-yavorovich** [comment]
fixed

**Comment by Saigets** [comment]
in template xml found 2 "antiminer" and 1 "antimner" today
best reagrds

**Comment by daniel-yavorovich** [comment]
@Saigets thank you, fixed too.
